# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/lucetre/Documents/semester/21s-hardware-system-design/lab10/src/lab10_ip_repo/myip_1.0/src/clk_wiz_0_4/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: c:/Users/lucetre/Documents/semester/21s-hardware-system-design/lab10/src/lab10_ip_repo/myip_1.0/src/clk_wiz_0_4/clk_wiz_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/lucetre/Documents/semester/21s-hardware-system-design/lab10/src/lab10_ip_repo/myip_1.0/src/clk_wiz_0_4/clk_wiz_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/lucetre/Documents/semester/21s-hardware-system-design/lab10/src/lab10_ip_repo/myip_1.0/src/clk_wiz_0_4/clk_wiz_0_ooc.xdc
