webtalk_init -webtalk_dir C:/lab06-jw/lab06.sim/sim_1/behav/xsim/xsim.dir/tb_my_pe_controller_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Apr 18 23:01:52 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "5b8375b1-5814-421d-bd0a-cafd5df76d70" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3690017fcb8e40fc86689ad79da035e5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "209" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 3 2200G with Radeon Vega Graphics    " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3500 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "4.95_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "16848_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1175613057 -regid "" -xml C:/lab06-jw/lab06.sim/sim_1/behav/xsim/xsim.dir/tb_my_pe_controller_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/lab06-jw/lab06.sim/sim_1/behav/xsim/xsim.dir/tb_my_pe_controller_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/lab06-jw/lab06.sim/sim_1/behav/xsim/xsim.dir/tb_my_pe_controller_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
