#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.3 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Jun 17 21:42:29 KST 2021
# SW Build 2405991 on Thu Dec  6 23:36:41 MST 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim tb_mm_multiplier_behav -key {Behavioral:sim_1:Functional:tb_mm_multiplier} -tclbatch tb_mm_multiplier.tcl -view /csehome/lgm0905/21s-hardware-system-design/Project/proj/V1_Quantization/Verilog/mm_mul/tb_mm_multiplier_behav.wcfg -log simulate.log
