# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/floating_point_MAC/floating_point_MAC.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==floating_point_MAC || ORIG_REF_NAME==floating_point_MAC} -quiet] -quiet
